# Numpy

Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4]
np.array(lst)

array([1, 2, 3, 4])

above is single dimension array




In [6]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

np.array([lst1,lst2,lst3])

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [7]:
arr1 = np.array([lst1,lst2,lst3])
arr1.shape

(3, 5)

# indexing

In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[1 2 3 4 5 6]


In [19]:
arr[2:]

array([3, 4, 5, 6])

In [20]:
arr[2:3]

array([3])

In [21]:
arr[:-3]

array([1, 2, 3])

In [22]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [23]:
arr1[:,1]

array([2, 3, 4])

# EDA - exploratory data analysis

In [25]:
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
arr[arr<2]

array([1])

In [27]:
# mechanism to creat an array

In [29]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [40]:
np.arange(1,100,10).reshape(1,10,1)

array([[[ 1],
        [11],
        [21],
        [31],
        [41],
        [51],
        [61],
        [71],
        [81],
        [91]]])